# Dotfiles
export DOTFILES_ROOT="$HOME/.dotfiles"
export PATH="$DOTFILES_ROOT/bin:$PATH"

# ZPlug
export ZPLUG_ROOT="$HOME/.zplug"

if [ -d "$ZPLUG_ROOT" ]; then
  source "$HOME/.zplug.zshrc"
fi

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"

if [ -d "$PYENV_ROOT" ]; then
  export PATH="$PYENV_ROOT/bin:$PATH"

  eval "$(pyenv init --path)"
fi

# Nodenv
export NODENV_ROOT="$HOME/.nodenv"

if [ -d "$NODENV_ROOT" ]; then
  export PATH="$NODENV_ROOT/bin:$PATH"

  eval "$(nodenv init -)"
fi

# Yarn
export PATH="$HOME/.yarn/bin:$PATH"

# Direnv
if type 'direnv' > /dev/null; then
  export EDITOR='code'
  eval "$(direnv hook zsh)"
fi

# Project Templates
export PATH="$HOME/.project-templates/bin:$PATH"

# Aliases
alias c='clear'
alias ls='ls --color=always'

# Load local zshrc
if [ -f "$HOME/.zshrc.local" ]; then
  source "$HOME/.zshrc.local"
fi
